default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: link-modify_development

test:
  <<: *default
  database: link-modify_test

  <<: *default
  database: link-modify_production
