development:
  adapter: postgresql
  encoding: unicode
  database: link-modify_development
  pool: 5
  timeout: 5000
  host:  localhost

test:
  adapter: postgresql
  database: link-modify_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: link-modify_production
  pool: 5
  timeout: 5000
